### ISSUE TITLE
Trouble setting up the project

### ISSUE THREAD

**Issue by DXGatech** [misa-j/social-network#3]
Steps to reproduce on Ubuntu L18.04: 
1. use git to clone the project locally
2. create variables.env in root directory, setting host to localhost:3000(since my nodejs starts at 3000)
3. change the window.location.hostname variable to localhost:3000 as well
4. change the proxy address to localhost:3000
This results in a bad request in Ubuntu with NodeJS v10 and a Request Header Too Long error in windows NodeJS v14
Am I doing something wrong?

**Comment by misa-j** [comment]
Project is based on create-react-app and its running on port 3000 so you cant have that and nodejs on same port
also HOST should be your local ip on port 5000 if you choose that port for nodejs (its already running on port 5000)
HOST=http://192.168.0.21:5000
and put same thing for  window.location.hostname

**Comment by misa-j** [comment]
and you should run `npm run dev` in root directory

**Comment by DXGatech** [comment]
HI, I have solved the issue by correcting my MongoDB connection URL. Thank you for clarifying
